---
language: python

python:
  - '3.7'

matrix:
  include:
    - os: linux
      dist: xenial

before_install:
  - sudo apt update

install:
  - sudo apt install -y bats git

before_script:
  - chmod +x testme.sh

script:
  - ./testme.sh -t
